version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: ${DOTNET_SDK_VERSION}

    env_file:
      - .env

    volumes:
      - ../..:/workspaces:cached
    
    network_mode: service:keycloak

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 8082:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres-data:
